Fixupcpp
d-SEAMS/seams-core pull request #40
Opened 2023-08-15 17:34 UTC by RuhiRG

I tried to clone pyseam in my Macos, it threw some errors. I did the following to fixup:

1. I had to match the cpp standard of pyseams and seams-core to 14.
2. I had to change the global argument to project agrument.
3. I had to add new dependency. (this is to make it easier to use in pyseams)

I opened a [Macos](https://github.com/d-SEAMS/seams-core/issues/25) issue in the beginning. This pull request will resolve it.

2023-08-15 22:21 UTC, HaoZeke commented
This will be easier to review after being rebased on #38

2023-08-16 17:26 UTC, HaoZeke requested changes

2023-08-16 17:26 UTC, HaoZeke commented on meson.build
I think the changes here can be cleanly merged onto main, without #38, could you remove other commits for this PR?

2023-08-23 14:49 UTC, RuhiRG commented on meson.build
OK, I think I did that.

2023-08-23 15:52 UTC, merged

2023-08-23 17:05 UTC, HaoZeke commented on meson.build
> +  default_options : ['warning_level=3', 'cpp_std=c++14'])
This is a little complicated, `sol2` v.3 requires at-least C++17.